/* eslint-disable react-hooks/rules-of-hooks */
import Footer from "@/app/(commonLayout)/components/shared/Footer";
import NavBar from "@/app/(commonLayout)/components/shared/Navbar";
import type { Metadata } from "next";
import Sidebar from "./components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default function userDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar />
      {/* Layout with Sidebar and Main content */}
      <div className="flex">
        {/* Sidebar */}
        <Sidebar />
        {/* Main Content */}
        <main className="flex-1 p-6">{children}</main>
      </div>
      <Footer />
    </div>
  );
}
